//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kdeneme
    {
        public string Kullanıcı_Adı { get; set; }
        public string Şifre { get; set; }
    }
}
